# Generated by Django 5.1.4 on 2025-01-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_resume", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plugin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("model", models.CharField(blank=True, max_length=255, null=True)),
                ("prompt", models.TextField()),
                ("module", models.TextField()),
                ("form_template", models.TextField()),
                ("content_template", models.TextField()),
            ],
        ),
    ]
